// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CardContainer: typeof import('./src/components/CardContainer/CardContainer.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('element-plus/es')['ElInput']
    MoveCard: typeof import('./src/components/MoveCard/MoveCard.vue')['default']
    NavItem: typeof import('./src/components/NavItem/NavItem.vue')['default']
    NavList: typeof import('./src/components/NavList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingItem: typeof import('./src/components/SettingItem.vue')['default']
  }
}

export {}
